### ISSUE TITLE
Survey banner

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual-backlog#114] opened 2019-07-23 10:00 UTC
## What
Survey banner

See GitHub issue: https://github.com/nhsuk/nhsuk-frontend/issues/399

More details to follow.

**Comment by AdamChrimes** [comment] 2019-09-02 12:10
Duplicate of https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/151

**Closed by AdamChrimes** 2019-09-02 12:10 UTC
Labels: component, help-wanted, needs-more-work
