### ISSUE TITLE
coronavirus (COVID-19)

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#227] opened 2020-03-24 12:29 UTC
We've added a new entry for coronavirus to the A to Z of NHS health writing: https://service-manual.nhs.uk/content/a-to-z-of-nhs-health-writing#coronavirus-(covid-19)

Please share any content-related research around coronavirus here.

**Comment by davidhunter08** [comment] 2020-05-18 08:19
Looks like a duplicate of #228. Closing issue.

**Closed by davidhunter08** 2020-05-18 08:19 UTC
